# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['api/main.py'],
    pathex=['api'],
    binaries=[],
    datas=[
        ('api', 'api'),
        ('ml', 'ml'),
        ('frontend/dist', 'frontend-dist'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'routes',
        'routes.snapshot',
        'routes.history',
        'routes.sentiment',
        'routes.anomalies',
        'routes.market',
        'routes.watchlist',
        'routes.websocket',
        'db',
        'db.session',
        'db.models',
        'ingestion',
        'ingestion.base',
        'ingestion.yahoo',
        'ingestion.news',
        'ingestion.reddit',
        'ingestion.alphavantage',
        'ingestion.finnhub',
        'analysis',
        'interpreter',
        'glossary',
        'config',
        'cache',
        'validation',
        'logging_config',
        'middleware',
        'ml',
        'ml.features',
        'ml.trend',
        'ml.anomaly',
        'ml.sentiment',
        'structlog',
        'sqlalchemy',
        'sqlalchemy.dialects.sqlite',
        'sklearn',
        'sklearn.ensemble',
        'sklearn.preprocessing',
        'nltk',
        'nltk.sentiment',
        'nltk.sentiment.vader',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='market-analyst-api',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='market-analyst-api',
)
